# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: df18fad58db5228f0c705e45c4eb16126cea21902c702e6c8c1213a739c6bd612cbb6700cbb49738ebac502a099a6372d2e5b571dbccf9f4887de6b3f0a8ffcf

test:
  secret_key_base: 130c6083289d117ed10d824c453b31ca5b8cf2b23798e4e685221b577a92e5d7a4c6519a7ba3477a34219290ac069e09f76dc291532a5c5cbcce70df01be679d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
